spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_JDBC_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-postgres.sql
spring.sql.init.data-locations=classpath:data-postgres.sql

spring.h2.console.enabled=false

server.port=${PORT:8080}
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
server.forward-headers-strategy=framework